name: Build and Deploy
on:
  push:
    branches:
      - vue

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2 

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          ${{ runner.os }}-

    - name: Install and Build 🔧 
      run: |
        npm ci --legacy-peer-deps
        npm run build

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-deployment
        folder: dist # The build folder
        target-folder: './'  # This ensures the contents of dist are pushed to the root
        clean: true
        token: ${{ secrets.GITHUB_TOKEN }}
